### ISSUE TITLE
toast and example.com

### ISSUE THREAD

**Issue by matti** [matti/superbara#2]
<img width="1177" alt="toast" src="https://user-images.githubusercontent.com/3893/40191332-d6112c44-5a09-11e8-8abd-9f1dd48c0c79.png">

https://github.com/matti/superbara/blob/master/lib/superbara.rb#L90-L127

**Comment by aom** [comment]
You'll have to have more reset styles for `__superbaraToastContainerElem`.

Webmaster of example.com has decided to style all `<DIV>` tags

```css
div {
    width: 600px;
    margin: 5em auto;
    padding: 50px;
    background-color: #fff;
    border-radius: 1em;
}
```

`Margin` is causing the huh space, `border-radius` is causing rounded corners and finally `padding` makes the element overflow the page.

I'd suggest adding few more reset lines from [Meyer's example](https://meyerweb.com/eric/tools/css/reset/):

```
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
```

Few additional inspired by example.com:

```
  border-radius: 0;
  display: block;
```
